import { useState } from "react";
import { Sparkles } from "lucide-react";
import LegalModal from "./LegalModal";
// Using the uploaded logo directly
const caboWaboLogo = "/lovable-uploads/2ae20f8e-51bb-449e-80aa-e850451395d5.png";

const Footer = () => {
  const [activeModal, setActiveModal] = useState<string | null>(null);

  const privacyPolicyContent = `CaboWabo values your privacy and is committed to protecting your personal information. We collect only the information necessary to provide you with personalized stories and a great user experience. This may include your name, email address, and story preferences.

All stories and images generated are stored securely and are only accessible to you. We do not share your personal information or generated content with third parties, except as required to provide our services (such as using OpenAI for story generation and Supabase for storage).

We do not use your data for advertising or sell it to anyone. You may delete your account and all associated data at any time from the app settings.

If you have any questions about your privacy, please contact us at support@cabowabo.app.`;

  const termsOfServiceContent = `By using CaboWabo, you agree to these Terms of Service ("Terms") in addition to our Privacy Statement and License Agreement.

1. Acceptable Use
You agree to use the app for personal, non-commercial purposes only. You must not misuse the app or its content. All stories and images generated are for entertainment and educational purposes.

2. Third-Party Services
CaboWabo uses third-party services (OpenAI for story generation and Supabase for data storage) to provide our services. We are not responsible for any content generated by these third-party services.

3. Notifications
By using this app, you consent to receive notifications from CaboWabo regarding important updates, new features, and relevant information to enhance your experience. You may manage your notification preferences in your device settings at any time.

4. Changes to Terms
We reserve the right to update these terms at any time. Continued use of the app constitutes acceptance of any changes.

5. Contact
For questions about these Terms of Service, contact support@cabowabo.app.

Last updated: June 2025`;

  const handleModalOpen = (modalType: string) => {
    setActiveModal(modalType);
  };

  const handleModalClose = () => {
    setActiveModal(null);
  };
  return (
    <footer className="py-12 px-4 bg-foreground text-background">
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center space-x-3 mb-4">
              <img 
                src={caboWaboLogo} 
                alt="CaboWabo" 
                className="h-8 w-auto"
              />
            </div>
            <p className="text-background/80 max-w-md leading-relaxed">
              Creating magical, personalized bedtime stories that spark imagination and bring families closer together.
            </p>
          </div>
          
          {/* Links */}
          <div>
            <h4 className="font-semibold mb-4">Product</h4>
            <ul className="space-y-2 text-background/80">
              <li><a href="#" className="hover:text-cabo-teal transition-colors">How it Works</a></li>
              <li><a href="#" className="hover:text-cabo-teal transition-colors">Pricing</a></li>
              <li><a href="#" className="hover:text-cabo-teal transition-colors">Sample Stories</a></li>
              <li><a href="#" className="hover:text-cabo-teal transition-colors">FAQ</a></li>
            </ul>
          </div>
          
          <div>
            <h4 className="font-semibold mb-4">Company</h4>
            <ul className="space-y-2 text-background/80">
              <li><a href="#" className="hover:text-cabo-teal transition-colors">About Us</a></li>
              <li>
                <button 
                  onClick={() => handleModalOpen('privacy')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  Privacy Policy
                </button>
              </li>
              <li>
                <button 
                  onClick={() => handleModalOpen('terms')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  Terms of Service
                </button>
              </li>
              <li><a href="#" className="hover:text-cabo-teal transition-colors">Contact</a></li>
            </ul>
          </div>
        </div>
        
        <div className="border-t border-background/20 mt-8 pt-8 text-center text-background/60">
          <p>&copy; 2024 CaboWabo. All rights reserved. Made with ❤️ for families everywhere.</p>
        </div>
      </div>

      {/* Legal Modals */}
      <LegalModal
        isOpen={activeModal === 'privacy'}
        onClose={handleModalClose}
        title="Privacy Policy"
        content={privacyPolicyContent}
      />
      <LegalModal
        isOpen={activeModal === 'terms'}
        onClose={handleModalClose}
        title="Terms of Service"
        content={termsOfServiceContent}
      />
    </footer>
  );
};

export default Footer;