import { useState } from "react";
import { Sparkles, Facebook, Twitter, Instagram, Youtube } from "lucide-react";
import LegalModal from "./LegalModal";
import TikTokIcon from "./TikTokIcon";
// Using the uploaded logo directly
const caboWaboLogo = "/lovable-uploads/2ae20f8e-51bb-449e-80aa-e850451395d5.png";

const Footer = () => {
  const [activeModal, setActiveModal] = useState<string | null>(null);

  const privacyPolicyContent = `CaboWabo values your privacy and is committed to protecting your personal information. We collect only the information necessary to provide you with personalized stories and a great user experience. This may include your name, email address, and story preferences.

All stories and images generated are stored securely and are only accessible to you. We do not share your personal information or generated content with third parties, except as required to provide our services (such as using OpenAI for story generation and Supabase for storage).

We do not use your data for advertising or sell it to anyone. You may delete your account and all associated data at any time from the app settings.

If you have any questions about your privacy, please contact us at support@cabowabo.app.`;

  const termsOfServiceContent = `By using CaboWabo, you agree to these Terms of Service ("Terms") in addition to our Privacy Statement and License Agreement.

1. Acceptable Use
You agree to use the app for personal, non-commercial purposes only. You must not misuse the app or its content. All stories and images generated are for entertainment and educational purposes.

2. Third-Party Services
CaboWabo uses third-party services (OpenAI for story generation and Supabase for data storage) to provide our services. We are not responsible for any content generated by these third-party services.

3. Notifications
By using this app, you consent to receive notifications from CaboWabo regarding important updates, new features, and relevant information to enhance your experience. You may manage your notification preferences in your device settings at any time.

4. Changes to Terms
We reserve the right to update these terms at any time. Continued use of the app constitutes acceptance of any changes.

5. Contact
For questions about these Terms of Service, contact support@cabowabo.app.

Last updated: June 2025`;

  const licenseAgreementContent = `This License Agreement ("Agreement") is between you and CaboWabo ("we," "us," or "our") regarding your use of the CaboWabo mobile application ("App").

1. License Grant
Subject to your compliance with this Agreement, our Terms of Service, and Privacy Statement, we grant you a limited, non-exclusive, non-transferable, revocable license to use the App on your personal device for personal, non-commercial purposes.

2. Acceptable Use
You agree to use the App only for lawful purposes and in accordance with this Agreement. You may not:

• Use the App for any commercial purpose
• Attempt to reverse engineer, decompile, or disassemble the App
• Remove or alter any copyright, trademark, or other proprietary notices
• Use the App to generate inappropriate or harmful content
• Share your account credentials with others

3. Content and Privacy
• The App generates AI-powered stories based on information you provide
• You are responsible for the accuracy and appropriateness of information you input
• Our Privacy Statement governs how we collect, use, and protect your information
• We do not store or share your children's personal information beyond what's necessary for story generation

4. Disclaimer of Warranties
THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

5. Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP.

6. Termination
We may terminate this license at any time if you fail to comply with this Agreement, our Terms of Service, or Privacy Statement. Upon termination, you must cease all use of the App.

7. Governing Law
This Agreement is governed by the laws of the United States, without regard to conflict of law principles.

8. Changes to Agreement
We may modify this Agreement at any time. Continued use of the App constitutes acceptance of any changes.

By using the App, you acknowledge that you have read, understood, and agree to be bound by this Agreement, our Terms of Service, and Privacy Statement.

Last updated: June 2025`;

  const cookiePolicyContent = `CaboWabo uses cookies to improve your browsing experience and understand how our site is used. By continuing to use this site, you agree to our use of cookies.

We use:
• Essential cookies to enable site functionality.
• Analytics cookies (e.g., Google Analytics) to measure usage and improve content.

You can manage or delete cookies in your browser settings at any time.

For more details, please see our Privacy Policy.

Last updated: July 2024`;

  const handleModalOpen = (modalType: string) => {
    setActiveModal(modalType);
  };

  const handleModalClose = () => {
    setActiveModal(null);
  };
  return (
    <footer className="py-12 px-4 bg-foreground text-background">
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center space-x-3 mb-4">
              <img 
                src={caboWaboLogo} 
                alt="CaboWabo" 
                className="h-8 w-auto"
              />
            </div>
            <p className="text-background/80 max-w-md leading-relaxed mb-6">
              Creating magical, personalized bedtime stories that spark imagination and bring families closer together.
            </p>
            
            {/* Social Media Icons */}
            <div className="flex space-x-4">
              <a href="#" className="text-background/60 hover:text-cabo-teal transition-colors">
                <Facebook size={20} />
              </a>
              <a href="#" className="text-background/60 hover:text-cabo-teal transition-colors">
                <Twitter size={20} />
              </a>
              <a href="#" className="text-background/60 hover:text-cabo-teal transition-colors">
                <Instagram size={20} />
              </a>
              <a href="#" className="text-background/60 hover:text-cabo-teal transition-colors">
                <Youtube size={20} />
              </a>
              <a href="#" className="text-background/60 hover:text-cabo-teal transition-colors">
                <TikTokIcon size={20} />
              </a>
            </div>
          </div>
          
          <div>
            <h4 className="font-semibold mb-4">Company</h4>
            <ul className="space-y-2 text-background/80">
              <li><a href="#" className="hover:text-cabo-teal transition-colors">About Us</a></li>
              <li>
                <button 
                  onClick={() => handleModalOpen('privacy')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  Privacy Policy
                </button>
              </li>
              <li>
                <button 
                  onClick={() => handleModalOpen('cookies')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  Cookie Policy
                </button>
              </li>
              <li>
                <button 
                  onClick={() => handleModalOpen('terms')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  Terms of Service
                </button>
              </li>
              <li>
                <button 
                  onClick={() => handleModalOpen('license')}
                  className="hover:text-cabo-teal transition-colors text-left"
                >
                  License Agreement
                </button>
              </li>
              <li><a href="#" className="hover:text-cabo-teal transition-colors">Contact</a></li>
            </ul>
          </div>
        </div>
        
        <div className="border-t border-background/20 mt-8 pt-8 text-center text-background/60">
          <p>&copy; 2024 CaboWabo. All rights reserved. Made with ❤️ for families everywhere.</p>
        </div>
      </div>

      {/* Legal Modals */}
      <LegalModal
        isOpen={activeModal === 'privacy'}
        onClose={handleModalClose}
        title="Privacy Policy"
        content={privacyPolicyContent}
      />
      <LegalModal
        isOpen={activeModal === 'cookies'}
        onClose={handleModalClose}
        title="Cookie Policy"
        content={cookiePolicyContent}
      />
      <LegalModal
        isOpen={activeModal === 'terms'}
        onClose={handleModalClose}
        title="Terms of Service"
        content={termsOfServiceContent}
      />
      <LegalModal
        isOpen={activeModal === 'license'}
        onClose={handleModalClose}
        title="License Agreement"
        content={licenseAgreementContent}
      />
    </footer>
  );
};

export default Footer;